name: latian
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_fonts: 
  introduction_screen: ^3.1.12
  image_picker: 1.0.4
  lottie: 2.6.0
  convex_bottom_bar: 3.2.0
  flutter: 
    sdk: flutter
  webview_flutter: ^4.4.1
  http: ^1.1.0
  flutter_staggered_grid_view: ^0.4.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

